name: Update Python Docker Image versions

on:
  schedule:
    - cron:  '0 5 * * *' # Every day at 05:00 UTC

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Update Python Docker Image
        run: ./scripts/pipeline.py update --python
